<?php
/**
 * seo-engine.php
 * Generates the full <head> block for GryphalCode pages.
 * It reads cached data from assets/seo/daily_data.json (generated by daily_seo_fetch.php).
 * All values are escaped to prevent injection.
 */

$cacheFile = __DIR__ . '/assets/seo/daily_data.json';
$cache = [];
if (file_exists($cacheFile)) {
    $json = file_get_contents($cacheFile);
    $cache = json_decode($json, true);
}

// Fallback defaults if cache missing or incomplete
$trends = $cache['trends'] ?? [];
$autocomplete = $cache['autocomplete'] ?? [];
$news = $cache['news'] ?? [];
$internalLinkCount = $cache['internal_links'] ?? 0;

// Build keyword list: combine trends + autocomplete (unique, limit 10)
$keywords = array_unique(array_merge($trends, $autocomplete));
$keywords = array_slice($keywords, 0, 10);
$keywordsString = htmlspecialchars(implode(', ', $keywords), ENT_QUOTES);

// Build description from top trends (max 150 chars)
$description = 'Latest tech trends: ' . implode(', ', array_slice($trends, 0, 5));
$description = htmlspecialchars($description, ENT_QUOTES);

// Build JSON‑LD schema (static, with dynamic description)
$schema = [
    '@context' => 'https://schema.org',
    '@type' => 'WebPage',
    'name' => $keywordsString,
    'description' => $description,
    'url' => (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] === 'on' ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI'],
    'provider' => [
        '@type' => 'Organization',
        'name' => 'GryphalCode',
        'url' => 'https://gryphalcode.com',
        'logo' => 'https://gryphalcode.com/assets/images/logo/logo.webp'
    ]
];
$schemaJson = json_encode($schema, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT);

// Build the head block
$headBlock = "<meta name=\"ai-search-readiness\" content=\"optimized\" />\n";
$headBlock .= "<meta name=\"answer-engine-optimization\" content=\"high-visibility\" />\n";
$headBlock .= "<meta name=\"generative-engine-targeting\" content=\"AI Overviews, SGE, LLM-Search\" />\n";
$headBlock .= "<meta content=\"IN-TN, IN-KL\" name=\"geo.region\" />\n";
$headBlock .= "<meta content=\"11.0168;76.9558\" name=\"geo.position\" />\n";
$headBlock .= "<meta content=\"Coimbatore, Tamil Nadu, Kerala, India - Serving All States Nationwide\" name=\"geo.placename\" />\n";
$headBlock .= "<meta content=\"11.0168, 76.9558\" name=\"ICBM\" />\n";
$headBlock .= "<meta http-equiv=\"Content-Security-Policy\" content=\"default-src 'self' https: data: 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' data: https://fonts.gstatic.com; connect-src 'self' https://trends.google.com https://news.google.com https://suggestqueries.google.com\" />\n";
$headBlock .= "<meta name=\"keywords\" content=\"{$keywordsString}\" />\n";
$headBlock .= "<meta name=\"description\" content=\"{$description}\" />\n";
$headBlock .= "<script async src=\"https://www.googletagmanager.com/gtag/js?id=G-3J6X1HS36W\"></script>\n";
$headBlock .= "<script>window.dataLayer = window.dataLayer || [];function gtag(){dataLayer.push(arguments);}gtag('js', new Date());gtag('config', 'G-3J6X1HS36W');</script>\n";
$headBlock .= "<script type=\"application/ld+json\">" . $schemaJson . "</script>\n";

// Export variable for inclusion
?>
<?php echo $headBlock; ?>
